### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by SamuraiT**
# objective

- To introduce wagmi for hook for metamask
- To introduce chakra ui for css components

### CODE REVIEW

**Comment by geeknees** [comment]
wagmi is good and I agree with its introduction.

Are you familiar with chakra ui about? Since the portal is leaning toward Tailwind, I thought it would be better to lean toward Tailwind, if either is acceptable.

Personally, I don't touch either one very much, so it doesn't matter which one I use, but I would be happy if we could unify them into one.

If you are familiar with chakra ui, I think it would be better to move toward chakra ui.

**Comment by geeknees** [comment]
Is it realistic to unify the front-end CSS frameworks for the henkaku project? I did some research because they were more different than I expected.

- portal, discord landing - tailwind
- membership nft - chakra ui
- junrei - bootsrap 
- ipfs-uploader semantic-ui-css

**Comment by geeknees** [comment]
Yeah, I agree. Without Templates, tailwind is tough.

I've been thinking about it. If other projects are not being actively developed, I'm starting to feel that we don't need to think too much about unifying frameworks. The portal project looks like it could be changed now.

In that sense, I thought it would be better to agree on this with the members who are actively developing the project. 

@TatsuyaIshibe  @neila @hourglasshoro

If you have any comments, please add them. chakra ui is fine for me, so I Approve.

**Review by geeknees — APPROVED** [review]

**Comment by hourglasshoro** [comment]
> using Tailwind isn't good fit for prototyping and is actually against "component based architecture" unless we make full components.

I agree with this. Since tailiwind is a CSS wrapper, it gives you a lot of freedom, but it's not the right choice if you want to make it quickly.

> I've been thinking about it. If other projects are not being actively developed, I'm starting to feel that we don't need to think too much about unifying frameworks.

From the perspective of a new participant, the lack of a unified CSS framework may be momentarily confusing, but that person does not maintain everything, so it should be fine. However, for new projects in the future, it is best to limit yourself to two CSS frameworks at most. I agree with the choice of chakra UI as one of them because it is a relatively modern frame.

**Pull request merged**
